[versions]
androidGradlePlugin = "8.4.2"
kotlin = "1.9.0"
mapsSecrets = "2.0.1"
navigationSafeArgs = "2.5.2"
ksp = "1.9.0-1.0.13"

coreKtx = "1.7.0"
appcompat = "1.5.1"
material = "1.6.1"
constraintlayout = "2.1.4"
navigationFragmentKtx = "2.5.3"
navigationUiKtx = "2.5.3"
navigationFragment = "2.5.2"
lifecycleLiveDataKtx = "2.4.1"
lifecycleViewModelKtx = "2.4.1"
lifecycleViewModelCompose = "2.5.1"
activity = "1.10.1"
activityKtx = "1.6.0"
legacySupportV4 = "1.0.0"
coreSplashscreen = "1.0.0"
lottie = "5.2.0"
playServicesMaps = "18.1.0"
playServicesLocation = "21.0.1"
retrofit = "2.9.0"
converterGson = "2.5.0"
loggingInterceptor = "4.10.0"
coil = "1.4.0"
coilLegacy = "1.1.1"
camera = "1.1.0-beta02"
tensorflowLite = "0.0.0-nightly-SNAPSHOT"
tensorflowLiteSupport = "0.1.0"
dexter = "6.2.2"
chucker = "4.0.0"
junit4 = "4.13.2"
androidxJunit = "1.1.3"
espressoCore = "3.4.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLiveDataKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewModelKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewModelCompose" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
airbnb-lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
google-play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
google-play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-retrofit2-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
squareup-retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-legacy = { module = "io.coil-kt:coil", version.ref = "coilLegacy" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLite" }
tensorflow-lite-support = { module = "org.tensorflow:tensorflow-lite-support", version.ref = "tensorflowLiteSupport" }
karumi-dexter = { module = "com.karumi:dexter", version.ref = "dexter" }
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
junit = { module = "junit:junit", version.ref = "junit4" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maps-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "mapsSecrets" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigationSafeArgs" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

